url: http://ibmstreams.github.io/streamsx.documentation/
baseurl: 

# Site settings
title: IBM Streams 
description: "IBM Streams Development Guides"

# Build settings
markdown: kramdown
permalink: pretty
detach:  false