url: http://ibmstreams.github.io/streamsx.documentation/
baseurl: /streamsx.documentation

# Site settings
title: IBM Streams 
description: "IBM Streams Development Guides"

# Build settings
markdown: kramdown
permalink: pretty
detach:  false
port:    4001
host:   9.26.55.129

